root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = "APP_BIN=./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]
  include_dir = ["."]
  watch_dir = ["."]
  delay = 2000
  exclude_ext = ["air"]
[log]
  level = "debug"
  color = true
  time = true
